# Generated by Django 5.1.4 on 2024-12-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_pointofinterest_city_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_key', models.CharField(help_text='Key of the record being referenced', max_length=50)),
                ('context', models.CharField(help_text="Context of the validation (e.g., 'import', 'update')", max_length=50)),
                ('aggregate', models.CharField(help_text='High-level error category', max_length=50)),
                ('specialized_aggregate', models.CharField(help_text='Specific error subcategory', max_length=50)),
                ('description', models.CharField(help_text='Detailed description of the validation error', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['parent_key'], name='cities_vali_parent__6befe1_idx'), models.Index(fields=['context', 'aggregate'], name='cities_vali_context_4e4629_idx')],
            },
        ),
    ]
